#!/bin/bash
case $1 in
	ao) shift
		if [ 1 -eq $(echo "$1" | egrep -c "^(http(s)?|git)://*") ]; then
			git remote add origin $@
		else
			git remote add origin $(cat $HOME/.config/gr)$@
		fi
		;;
	ro) shift; git remote remove origin ;;
	a) shift; git remote add $@ ;;
	r) shift; git remote remove $@ ;;
	sh) shift; git remote set-head $@ ;;
	sb) shift; git remote set-branches $@ ;;
	sua) shift; git remote set-url --add $@ ;;
	sud) shift; git remote set-url --delete $@ ;;
	su) shift; git remote set-url $@ ;;
	p) shift; git remote prune $@ ;;
	u) shift; git remote update $@ ;;
	*) git remote $@
esac
