#!/bin/bash
case $1 in
	ao) shift
		if [ 1 -eq $(echo "$1" | egrep -c "^(http(s)?|git)://*") ]; then
			git remote add origin $@
		elif [ 1 -eq $(echo "$1" | egrep -c "^[^:]+:.+") ]; then
			nnnn="$(echo "$1" | perl -pe 's/([^:]+:).+/$1/')"
			nn="$(cat $HOME/.config/gr | wc -l)"
			in=2
			while (( $in <= $nn )); do
				hi="$(head -n $in $HOME/.config/gr | tail -n 1)"
				if [ 1 -eq $(echo "$hi" | egrep -c "^$nnnn") ]; then
					xD="$(echo "$1" | perl -pe 's/[^:]+:(.+)/$1/')"
					shift
					git remote add origin $(echo "$hi" | perl -pe 's/[^:]+:(.+)/$1/')$xD
					exit 0
				fi
				(( in++ ))
			done
			echo "Couldn't find provider $(echo "$nnnn" | perl -pe 's/:$//')"
		else
			git remote add origin $(head -n 1 $HOME/.config/gr)$@
		fi
		;;
	ro) shift; git remote remove origin ;;
	a)  shift
		qwdf="$1"
		shift
		if [ 1 -eq $(echo "$1" | egrep -c "^(http(s)?|git)://*") ]; then
			git remote add $qwdf $@
		elif [ 1 -eq $(echo "$1" | egrep -c "^[^:]+:.+") ]; then
			nnnn="$(echo "$1" | perl -pe 's/([^:]+:).+/$1/')"
			nn="$(cat $HOME/.config/gr | wc -l)"
			in=2
			while (( $in <= $nn )); do
				hi="$(head -n $in $HOME/.config/gr | tail -n 1)"
				if [ 1 -eq $(echo "$hi" | egrep -c "^$nnnn") ]; then
					xD="$(echo "$1" | perl -pe 's/[^:]+:(.+)/$1/')"
					shift
					git remote add $qwdf $(echo "$hi" | perl -pe 's/[^:]+:(.+)/$1/')$xD
					exit 0
				fi
				(( in++ ))
			done
			echo "Couldn't find provider $(echo "$nnnn" | perl -pe 's/:$//')"
		else
			git remote add $qwdf $(head -n 1 $HOME/.config/gr)$@
		fi
		;;
	r) shift; git remote remove $@ ;;
	sh) shift; git remote set-head $@ ;;
	sb) shift; git remote set-branches $@ ;;
	su) shift; git remote set-url $@ ;;
	sua) shift; git remote set-url --add $@ ;;
	sud) shift; git remote set-url --delete $@ ;;
	p) shift; git remote prune $@ ;;
	u) shift; git remote update $@ ;;
	*) git remote $@
esac
